<?php

return [
    'title'        => 'Reports',
    'generate'     => 'Generate Report',
    'export_pdf'   => 'Export PDF',
    'export_excel' => 'Export Excel',
    'date_from'    => 'From Date',
    'date_to'      => 'To Date',
    'r1_title'     => 'Full Beneficiary Report',
    'r2_title'     => 'Visits Report',
    'r3_title'     => 'Unvisited Beneficiaries',
    'r4_title'     => 'Group Activity',
    'r5_title'     => 'Medical Overview',
    'generated_at' => 'Generated at',
    'generated_by' => 'Generated by',
    'page'         => 'Page',
    'of'           => 'of',
    'no_data'      => 'No data to display',
    'r1_description' => 'Complete list of active beneficiaries',
    'r2_description' => 'Visit and call records for the selected period',
    'r3_description' => 'Beneficiaries not visited in over 30 days',
];
