<?php

return [
    'title'    => 'Beneficiaries',
    'singular' => 'Beneficiary',
    'add'      => 'Add Beneficiary',
    'edit'     => 'Edit Beneficiary',
    'view'     => 'View Beneficiary',

    'tab_basic'         => 'Basic Info',
    'tab_contact'       => 'Contact & Family',
    'tab_address'       => 'Address',
    'tab_medical'       => 'Medical Status',
    'tab_medications'   => 'Medications',
    'tab_medical_files' => 'Medical Files',
    'tab_visits'        => 'Visit History',
    'tab_scheduled'     => 'Scheduled Visits',
    'tab_prayer'        => 'Prayer Requests',
    'tab_audit'         => 'Audit Log',

    'full_name'    => 'Full Name',
    'photo'        => 'Photo',
    'photo_helper' => 'Supported: JPEG, PNG, GIF, WebP, SVG — Max size: 5 MB',
    'birth_date'   => 'Birth Date',
    'gender'       => 'Gender',
    'code'         => 'Code',
    'status'       => 'Status',

    'male'   => 'Male',
    'female' => 'Female',

    'active'   => 'Active',
    'inactive' => 'Inactive',
    'moved'    => 'Moved',
    'deceased' => 'Deceased',

    'phone'                => 'Phone',
    'whatsapp'             => 'WhatsApp',
    'facebook_url'         => 'Facebook',
    'instagram_url'        => 'Instagram',
    'whatsapp_beneficiary' => 'Beneficiary WhatsApp',
    'whatsapp_guardian'    => 'Guardian WhatsApp',

    'contact_section'   => 'Contact Information',
    'guardian_section'  => 'Guardian',
    'guardian_name'     => 'Guardian Name',
    'guardian_phone'    => 'Guardian Phone',
    'guardian_relation' => 'Relation',

    'family_section'    => 'Family Situation',
    'family_note'       => 'This is the beneficiary\'s biological family information, not the ministry service group.',
    'father_status'     => 'Father Status',
    'father_death_date' => 'Father Death Date',
    'mother_status'     => 'Mother Status',
    'mother_death_date' => 'Mother Death Date',
    'alive'             => 'Alive',
    'unknown'           => 'Unknown',
    'siblings_count'    => 'Siblings Count',
    'siblings_note'     => 'Siblings Note',

    'financial_section' => 'Financial Situation',
    'financial_status'  => 'Financial Status',
    'financial_notes'   => 'Financial Notes',
    'good'              => 'Good',
    'moderate'          => 'Moderate',
    'poor'              => 'Poor',
    'very_poor'         => 'Very Poor',

    'address_text'    => 'Address',
    'google_maps_url' => 'Google Maps Link',
    'area'            => 'Area',
    'governorate'     => 'Governorate',
    'open_map'        => 'Open Map',

    'assignment_section' => 'Ministry Assignment',
    'service_group'      => 'Service Group',
    'assigned_servant'   => 'Assigned Servant',

    'disability_type'     => 'Disability Type',
    'disability_degree'   => 'Disability Degree',
    'mild'                => 'Mild',
    'severe'              => 'Severe',
    'health_status'       => 'Health Status',
    'doctor_name'         => 'Doctor Name',
    'hospital_name'       => 'Hospital',
    'last_medical_update' => 'Last Medical Update',
    'medical_notes'       => 'Medical Notes',

    'created_by'         => 'Added by',
    'created_at'         => 'Added on',
    'never_visited'      => 'Never visited',
    'last_visit'         => 'Last visit',
    'days_without_visit' => ':days days without visit',
];
