<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Token Expiry (hours)
    |--------------------------------------------------------------------------
    |
    | The number of hours a registration token remains valid after generation.
    | After this period, the token will be rejected and a new one must be
    | generated by a leader.
    |
    */
    'token_expiry_hours' => (int) env('REGISTRATION_TOKEN_EXPIRY_HOURS', 72),

];
